# Generated by Django 4.1.7 on 2023-02-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=64, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'адреса',
            },
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(default=0, verbose_name='номер аудитории')),
                ('is_online', models.BooleanField(default=True, verbose_name='формат обучения')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.address', verbose_name='адрес аудитории')),
            ],
            options={
                'verbose_name': 'аудитория',
                'verbose_name_plural': 'аудитории',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категория',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='продолжительность обучения в днях')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название курса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='стоимость')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'курсы',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(default=0, verbose_name='номер группы')),
                ('date_start', models.DateField(blank=True, verbose_name='дата начала')),
                ('audience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.audience', verbose_name='аудитория')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
            },
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='#')),
                ('name', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'учебные материалы',
                'verbose_name_plural': 'учебные материалы',
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_paid_date', models.DateField(blank=True, verbose_name='дата 1-ой оплаты')),
                ('first_paid_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='сумма 1-ой оплаты')),
                ('sec_paid_date', models.DateField(blank=True, verbose_name='дата 2-ой оплаты')),
                ('sec_paid_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='сумма 2-ой оплаты')),
            ],
            options={
                'verbose_name': 'статус оплаты',
                'verbose_name_plural': 'статус оплаты',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='все права', max_length=20, null=True, unique=True, verbose_name='права пользователя ')),
            ],
            options={
                'verbose_name': 'разрешение',
                'verbose_name_plural': 'разрешение',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='студент', max_length=10, null=True, unique=True, verbose_name='роль пользователя')),
            ],
            options={
                'verbose_name': 'роль пользователя',
                'verbose_name_plural': 'роль пользователя',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='емайл')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.role', verbose_name='роль пользователя')),
            ],
            options={
                'verbose_name': 'пользователи',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.permission', verbose_name='права пользователя')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.role', verbose_name='статус пользователя')),
            ],
            options={
                'verbose_name': 'роль-разрешение',
                'verbose_name_plural': 'роль-разрешение',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(verbose_name='дата и время урока')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.lessonmaterial')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'урок',
            },
        ),
        migrations.CreateModel(
            name='GroupUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manager.group', verbose_name='номер группы')),
                ('user_id', models.ForeignKey(default='Иванов', on_delete=django.db.models.deletion.PROTECT, to='manager.user', verbose_name='студент')),
            ],
            options={
                'verbose_name': 'группа-юзер',
                'verbose_name_plural': 'группа-юзер',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=350, null=True, verbose_name='отзыв')),
                ('user', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='manager.user', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'отзывы',
                'verbose_name_plural': 'отзывы',
            },
        ),
    ]
