# Generated by Django 4.1.7 on 2023-02-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='is_online',
            field=models.BooleanField(verbose_name='онлайн'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='number',
            field=models.SmallIntegerField(default=1, verbose_name='номер аудитории'),
        ),
    ]
